name: Hello World

on:
  push:
    branches:
     - 'main'

jobs:
 hello:  
   runs-on: ubuntu-latest
    
   steps:
     - name: Install Pytest
       run: |
         python -m pip install pytest
         
     - name: Run Unstable.py
       run: |
         python -m pytest 'Scissors-Paper-Stone/Unstable.py'
