name: Hello World

on:
  push:
    branches:
     - 'main'

python -m pip install pytest

jobs:
 hello:  
   runs-on: ubuntu-latest
    
   steps:
     - name: Run Unstable.py
       run: |
         python -m pytest 'Unstable.py'
